# Generated by Django 5.1 on 2026-03-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='suburb',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
