# Generated by Django 5.1 on 2026-04-01 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_name_customuser_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='postcode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
