# Generated by Django 5.1 on 2026-02-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_fundraiser_deadline_fundraiser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='location',
            new_name='suburb',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='postcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
